# Generated by Django 5.1.1 on 2024-09-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0003_papersize_paperthickness_papertype_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papersize',
            name='name',
        ),
    ]
