# Generated by Django 5.1.1 on 2024-09-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0004_remove_papersize_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersize',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pccapp.product'),
            preserve_default=False,
        ),
    ]
