# Generated by Django 5.1.1 on 2024-09-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0005_papersize_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaperSize',
            new_name='ProductSize',
        ),
    ]
