# Generated by Django 5.1.1 on 2024-09-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0006_rename_papersize_productsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
