# Generated by Django 5.1.1 on 2024-09-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0008_papersize_substrate_substratesize_substratethickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersize',
            name='name',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
