# Generated by Django 5.1.1 on 2024-09-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0009_papersize_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersize',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
