# Generated by Django 5.1.1 on 2024-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0011_product_min_quantity_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substratesize',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
