# Generated by Django 5.1.1 on 2024-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0012_alter_substratesize_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printing_cost',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='paperconfiguration',
            unique_together={('paper_type', 'paper_size', 'paper_thickness')},
        ),
        migrations.AlterUniqueTogether(
            name='substrateconfiguration',
            unique_together={('substrate', 'substrate_size', 'substrate_thickness')},
        ),
    ]
