# Generated by Django 5.1.1 on 2024-09-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccapp', '0013_product_printing_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='printing_cost',
        ),
    ]
